config/routes.rb
Rails.application.routes.draw do
  resources :status_updates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root controller: 'status_updates', action: 'index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status_update.rb
class StatusUpdate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/status_updates_controller.rb
class StatusUpdatesController < ApplicationController
  before_action :set_status_update, only: [:show, :edit, :update, :destroy]

  # GET /status_updates
  # GET /status_updates.json
  def index
    @status_updates = StatusUpdate.all
  end

  # GET /status_updates/1
  # GET /status_updates/1.json
  def show
  end

  # GET /status_updates/new
  def new
    @status_update = StatusUpdate.new
  end

  # GET /status_updates/1/edit
  def edit
  end

  # POST /status_updates
  # POST /status_updates.json
  def create
    @status_update = StatusUpdate.new(status_update_params)

    respond_to do |format|
      if @status_update.save
        format.html { redirect_to @status_update, notice: 'Status update was successfully created.' }
        format.json { render :show, status: :created, location: @status_update }
      else
        format.html { render :new }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_updates/1
  # PATCH/PUT /status_updates/1.json
  def update
    respond_to do |format|
      if @status_update.update(status_update_params)
        format.html { redirect_to @status_update, notice: 'Status update was successfully updated.' }
        format.json { render :show, status: :ok, location: @status_update }
      else
        format.html { render :edit }
        format.json { render json: @status_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_updates/1
  # DELETE /status_updates/1.json
  def destroy
    @status_update.destroy
    respond_to do |format|
      format.html { redirect_to status_updates_url, notice: 'Status update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_update
      @status_update = StatusUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_update_params
      params.require(:status_update).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/status_updates_helper.rb
module StatusUpdatesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twutter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/status_updates/_form.html.erb
<%= form_with(model: status_update, local: true) do |form| %>
  <% if status_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status_update.errors.count, "error") %> prohibited this status_update from being saved:</h2>

      <ul>
      <% status_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/status_updates/edit.html.erb
<h1>Editing Status Update</h1>

<%= render 'form', status_update: @status_update %>

<%= link_to 'Show', @status_update %> |
<%= link_to 'Back', status_updates_path %>

app/views/status_updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Status Updates</h1>

<div id="status-updates">
  <% @status_updates.each do |update| %>
    <div class="status-update">
      <p><%= update.body %></p>
      <small><%= update.created_at %></small>
    </div>
  <% end %>
</div>

<br>

<%= link_to 'New Status Update', new_status_update_path %>

app/views/status_updates/new.html.erb
<h1>New Status Update</h1>

<%= render 'form', status_update: @status_update %>

<%= link_to 'Back', status_updates_path %>

app/views/status_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @status_update.body %>
</p>

<%= link_to 'Edit', edit_status_update_path(@status_update) %> |
<%= link_to 'Back', status_updates_path %>